---
params:
  ref: "/data/SGSlab/kjohnson/reference/sars2/SARS-CoV2.fa"
  bamdir: "/data/SGSlab/kjohnson/autopsy/rep1/merged_bams"
  bam_ending: ".sars.sorted.merged.bbmap.bam"
  output: "/data/SGSlab/kjohnson/autopsy/rep1/"
  strain: "SARS"
  gtf_dir: "/data/SGSlab/kjohnson/reference/sars2"
  script_dir: "/data/SGSlab/kjohnson/autopsy/scripts/"
  venv_path: "/home/johnsonkate/penv/bin/activate"

divrge_param:
  mismatch: '2'
  gap_size: '5'
  align_length: '28'
  group_size: '5'
  ncores: "2"
  ninput: "1"

mod_params:
  subread_mod: "subread/2.0.3"
  samtools_mod: "samtools/1.16.1"
  python_mod: "python/3.8"
