---
params:
  ref: "/data/SGSlab/kjohnson/test/reference/h1n1/Cal07.09.cds.fasta"
  reads: "/data/SGSlab/kjohnson/test/rawfiles/"
  begin1: ""
  ending1: "_read1.fq.gz"
  begin2: ""
  ending2: "_read2.fq.gz"
  output: "/data/SGSlab/kjohnson/test/"
  maxindel: "3000"
  minindel: "5"
  adapters: "/usr/local/apps/trimmomatic/Trimmomatic-0.36/adapters/NexteraPE-PE.fa"
  strain: "H1N1"
  gigs: "4G"
  gtf_dir: "/data/SGSlab/kjohnson/test/reference/h1n1"
  script_dir: "/data/SGSlab/kjohnson/test/scripts/"
  venv_path: "/home/johnsonkate/divrge/bin/activate"

timo_params:
  segments: ['H1N1_PB2','H1N1_PB1','H1N1_PA','H1N1_HA','H1N1_NP','H1N1_MP','H1N1_NS']
  freq_cutoff: "0.001"
  cov_cutoff: "1"

divrge_param:
  mismatch: '2'
  gap_size: '5'
  align_length: '28'
  group_size: '5'
  ncores: "2"
  ninput: "1"

mod_params:
  subread_mod: "subread/2.0.1"
  samtools_mod: "samtools/1.14"
  python_mod: "python/3.8"
  trim_mod: "trimmomatic/0.39"
  trim_jar: "$TRIMMOMATIC_JAR"
  bbtools: "bbtools/38.96"
  bbtools_path: "/usr/local/apps/bbtools/38.96/bbmap_src/"
  bwa: "bwa/0.7.17"
  picard_mod: "picard/2.27.3"
  picard_jar: "$PICARD_JAR"
