---
params:
  ref: "/data/johnsonkate/test_hmh/reference/SARS-CoV2.fa"
  bamfiles: "/data/FluSeq/test/rmdups"
  begin: ""
  ending: ".SARS2.rmd.bbmap.bam"
  output: "/data/FluSeq/test/"
  strain: "SARS2"
  script_dir: "/data/johnsonkate/test_hmh/scripts/"
  venv_path: "/home/johnsonkate/divrge/bin/activate"

divrge_param:
  mismatch: '2'
  indel: '2'
  gap_size: '5'
  align_length: '28'
  group_size: '5'
  ncores: "4"
  nbams: "1"
  gap_type: "N"
  min_count: "10"
  qual_cutoff: "25"

mod_params:
  samtools_mod: "samtools/1.14"
  python_mod: "python/3.8"
  sambamba: "sambamba/1.0.1"